config/routes.rb
Rails.application.routes.draw do

  resources :messages do
    collection do
      get :sent
    end
  end

  resources :requests
  resources :carousels do
    collection do
      post :publish
      post :unpublish
      delete :destroy
    end
  end
  resources :announcements do
    collection do
      get :carousel
    end
  end
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :events
  resources :jobs
root to: 'home#index'
  get 'home/index'
  resources :home

  resources :graduations
  resources :batches do
    collection do
      post :action_import
    end
  end
  resources :campus
  resources :faculties
  resources :programmes
  devise_for :users
  resources :users

  resources :claim do
    collection do
      get :claim_account
      get :change
    end
  end

  resources :user_profiles do
    get :view_profile
    collection do
      post :upload_profile_picture
      get :privacy
      post :settings
    end
  end

  resources :find_users do
    collection do
      get :map_view
    end
  end

  resources :import do
    collection do
      post :import
      post :importing
    end
  end

  resources :members
  resources :employers do
    collection do
      post :search
      get  :search
    end
  end

end

app/models/_job.rb
class Job < ActiveRecord::Base
  belongs_to :user
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  include Bootsy::Container

  require 'carrierwave/orm/activerecord'
end

app/models/batch.rb
class Batch < ActiveRecord::Base
  has_many :graduations, dependent: :destroy

  RIVACY_OPTIONS = Array["Everyone", "Only Me", "My Batch", "My Programme"]
  MONTHS = Array[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
end

app/models/campu.rb
class Campu < ActiveRecord::Base
  validates :name, presence: true, allow_blank: false
  has_many :faculties,  dependent: :destroy
  has_many :graduations, dependent: :destroy
end

app/models/carousel.rb
class Carousel < ActiveRecord::Base
  mount_uploader :image, CarouselUploader
end

app/models/event.rb
class Event < ActiveRecord::Base
  include Bootsy::Container
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  validates :name, presence: true, allow_blank: false
  has_many :programmes,  dependent: :destroy
  belongs_to :campus
  has_many :graduations, dependent: :destroy

  include ::Importable
   IMPORT_ENABLED = {
     :name => {exact: "name", is_identifier: true}
   }
end

app/models/graduation.rb
class Graduation < ActiveRecord::Base
  belongs_to :user
  belongs_to :batch
  belongs_to :programme
  belongs_to :faculty
  belongs_to :campu

  include ::Importable
   IMPORT_ENABLED = {
     :user_id => {exact: "Student Id", is_identifier: false},
     :name => {exact: "Student Name", is_identifier: false},
     :last_name => {exact: "Last Name", is_identifier: false},
     :email => {exact: "Email", is_identifier: false},
     :alumni_key => {exact: "Alumni Key", is_identifier: false},
     :batch_id => {exact: "Batch", is_identifier: false},
     :programme_id => {exact: "Programme", is_identifier: false},
     :campu_id => {exact: "Campus", is_identifier: false},
     :faculty_id => {exact: "Faculty", is_identifier: false},
   }
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/programme.rb
class Programme < ActiveRecord::Base
  validates :name, presence: true, allow_blank: false

  has_many :graduations, dependent: :destroy
  belongs_to :faculty
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :is_current_city, :faculty, :programme, :batch, :campus
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  geocoded_by :city
  after_validation :geocode

  has_many :graduations, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :messages, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  PRIVACY_OPTIONS = Array["Everyone", "Only Me", "My Batch", "My Programme"]

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to user_profiles_url, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to user_profiles_url, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :company, :city, :country, :current, :from, :to, :experience, :skills).merge(:user_id => current_user.id)
    end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/campus_helper.rb
module CampusHelper
end

app/helpers/claim_helper.rb
module ClaimHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
  <%= semantic_form_for(@job) do |f| %>
      <% if @job.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

          <ul>
            <% @job.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="panel panel-default">
        <div class="panel-heading"><h1>Job</h1></div>
          <div class="panel-body">
            <div class="job-padding col-md-6" >
              <%= f.text_field :title, autofocus: true, placeholder: 'Title', :class => 'form-control' %>
            </div>

            <div class="job-padding col-md-6" >
              <%= f.text_field :company, placeholder: "Company", :class => 'form-control' %>
            </div>

            <div class="job-padding col-md-6" >
              <%= f.text_field :city, placeholder: 'City', :class => 'form-control' %>
            </div>

            <div class="job-padding col-md-6" >
              <%= f.text_field :country, placeholder: 'Country', :class => 'form-control' %>
            </div>

            <div class="job-padding col-md-2">
              <br>
              <%= f.input :current, label: "Current Job?"%>
            </div>

            <div class="job-padding col-md-5" >
              <%= f.input :from, :as => :date_select, :discard_year => false, :start_year => 1995,  :end_year => Date.current.year, :order => [:month, :year], :discard_day => true, :class => 'form-control' %>
            </div>

            <div class="job-padding col-md-5" >
              <%= f.input :to, :as => :date_select, :discard_month => false, :start_year => 1995,  :end_year => Date.current.year,  :order => [:month, :year], :discard_day => true, :class => 'form-control' %>
            </div>

            <div class="job-padding col-md-6" >
              <%= f.text_area :skills, placeholder: 'Skills', :class => 'form-control' %>
            </div>

            <div class="job-padding col-md-6" >
              <%= f.text_area :experience, placeholder: 'Description', :class => 'form-control' %>
            </div>

            <div class="job-padding col-md-6">
              <%= f.submit "Add Job", :class => 'btn-u' %>
              <%= link_to 'Back', user_profiles_path, class: 'btn-u btn-u-default' %>
            </div>
          </div>
        </div>
      </div>
  <% end %>

app/views/jobs/edit.html.erb
<div class="container content profile">
  <div class="col-md-12">
    <div class="profile-body margin-bottom-20">

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container col-sm-8">


<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>Job Title</th>
      <th>Company</th>
      <th>City</th>
      <th>Country</th>

      <th>
        From
      </th>
      <th>
        To
      </th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <% if job.user_id == current_user.id %>
        <tr>
          <td>
            <% if !job.title.nil?%>
              <%= job.title %>
            <% else %>
              N/A
            <% end %>
          </td>
          <td>
            <% if !job.company.nil? %>
                <%= job.company %>
              <% else %>
                N/A
            <% end %>
          </td>
          <td>
            <% if !job.city.nil? %>
              <%= job.city %>
              <% else %>
                N/A
            <% end %>
          </td>
          <td>
            <% if !job.country.nil? %>
              <%= job.country %>
            <% else %>
                N/A
            <% end %>
          </td>

          <td>
            <% if !job.from.nil? %>
              <%= job.from.strftime("%B") <<" "<< job.from.strftime("%Y") %>
              <% else %>
                N/A
            <% end %>
          </td>
          <td>
            <% if !job.to.nil? %>
              <%= job.to.strftime("%B") <<" "<< job.to.strftime("%Y") %>
              <% else %>
                N/A
            <% end %>
          </td>
          <td><%= link_to edit_job_path(job) do %><span class="glyphicon glyphicon-edit"></span> <% end %> </td>
          <td><%= link_to job, method: :delete, data: { confirm: 'Are you sure?' } do %> <span class="glyphicon glyphicon-remove"></span><% end %> </td>
        </tr>
        <% end %>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Job', new_job_path, :class => 'btn btn-primary btn-flat' %>
</div>

app/views/jobs/new.html.erb
<div class="container content">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>