config/routes.rb
Rails.application.routes.draw do

  resources :messages do
    collection do
      get :sent
    end
  end

  resources :requests
  resources :carousels do
    collection do
      post :publish
      post :unpublish
      delete :destroy
    end
  end
  resources :announcements do
    collection do
      get :carousel
    end
  end
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :events
  resources :jobs
root to: 'home#index'
  get 'home/index'
  resources :home

  resources :graduations
  resources :batches do
    collection do
      post :action_import
    end
  end
  resources :campus
  resources :faculties
  resources :programmes
  devise_for :users
  resources :users

  resources :claim do
    collection do
      get :claim_account
      get :change
    end
  end

  resources :user_profiles do
    get :view_profile
    collection do
      post :upload_profile_picture
      get :privacy
      post :settings
    end
  end

  resources :find_users do
    collection do
      get :map_view
    end
  end

  resources :import do
    collection do
      post :import
      post :importing
    end
  end

  resources :members
  resources :employers do
    collection do
      post :search
      get  :search
    end
  end

end

app/models/_job.rb
class Job < ActiveRecord::Base
  belongs_to :user
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  include Bootsy::Container

  require 'carrierwave/orm/activerecord'
end

app/models/batch.rb
class Batch < ActiveRecord::Base
  has_many :graduations, dependent: :destroy

  RIVACY_OPTIONS = Array["Everyone", "Only Me", "My Batch", "My Programme"]
  MONTHS = Array[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
end

app/models/campu.rb
class Campu < ActiveRecord::Base
  validates :name, presence: true, allow_blank: false
  has_many :faculties,  dependent: :destroy
  has_many :graduations, dependent: :destroy
end

app/models/carousel.rb
class Carousel < ActiveRecord::Base
  mount_uploader :image, CarouselUploader
end

app/models/event.rb
class Event < ActiveRecord::Base
  include Bootsy::Container
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  validates :name, presence: true, allow_blank: false
  has_many :programmes,  dependent: :destroy
  belongs_to :campus
  has_many :graduations, dependent: :destroy

  include ::Importable
   IMPORT_ENABLED = {
     :name => {exact: "name", is_identifier: true}
   }
end

app/models/graduation.rb
class Graduation < ActiveRecord::Base
  belongs_to :user
  belongs_to :batch
  belongs_to :programme
  belongs_to :faculty
  belongs_to :campu

  include ::Importable
   IMPORT_ENABLED = {
     :user_id => {exact: "Student Id", is_identifier: false},
     :name => {exact: "Student Name", is_identifier: false},
     :last_name => {exact: "Last Name", is_identifier: false},
     :email => {exact: "Email", is_identifier: false},
     :alumni_key => {exact: "Alumni Key", is_identifier: false},
     :batch_id => {exact: "Batch", is_identifier: false},
     :programme_id => {exact: "Programme", is_identifier: false},
     :campu_id => {exact: "Campus", is_identifier: false},
     :faculty_id => {exact: "Faculty", is_identifier: false},
   }
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/programme.rb
class Programme < ActiveRecord::Base
  validates :name, presence: true, allow_blank: false

  has_many :graduations, dependent: :destroy
  belongs_to :faculty
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :is_current_city, :faculty, :programme, :batch, :campus
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  geocoded_by :city
  after_validation :geocode

  has_many :graduations, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :messages, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  PRIVACY_OPTIONS = Array["Everyone", "Only Me", "My Batch", "My Programme"]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @announcements = Announcement.order("created_at desc").limit(3)
    @events = Event.order("created_at desc").limit(3)
    @carousels = Carousel.where(:is_published => true)
  end
end

app/helpers/campus_helper.rb
module CampusHelper
end

app/helpers/claim_helper.rb
module ClaimHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_announcements.html.erb
<div class="headline"><h2>Recent Announcements</h2></div>
<div class="row news-v2 margin-bottom-50">
  <% if @announcements.any? %>
    <% @announcements.each do |announcement| %>
      <div class="col-sm-4 sm-margin-bottom-30">
        <div class="news-v2-badge">
          <%= image_tag('img18.jpg', class: 'img-responsive') %>
          <p>
            <span><%= announcement.created_at.strftime("%d")%></span>
            <small><%= announcement.created_at.strftime("%b")%></small>
          </p>
        </div>
        <div class="news-v2-desc">
          <h3><%= link_to  announcement.title.html_safe, announcement_path(id: announcement.id)%></h3>
          <p><%= announcement.content.truncate(100).html_safe%></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="headline"><h2>Latest Events</h2></div>
<div class="row news-v2 margin-bottom-50">
  <div class="row news-v2 margin-bottom-50">
    <% if @events.any? %>
      <% @events.each do |event| %>
        <div class="col-sm-4 sm-margin-bottom-30">
          <div class="news-v2-badge">
            <%= image_tag('img18.jpg', class: 'img-responsive') %>
            <p>
              <span><%= event.created_at.strftime("%d")%></span>
              <small><%= event.created_at.strftime("%b")%></small>
            </p>
          </div>
          <div class="news-v2-desc">
            <h3><%= link_to  event.title.html_safe,   event_path(id: event.id)%></h3>
            <p><%= event.description.truncate(100).html_safe%></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/home/_carousel.html.erb
<div id="myCarousel" class="carousel slide "  data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
  <!--  <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li> !-->
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner " role="listbox">
    <div class="item active" >
      <div class="carousel-content">
        <h1 class="carousel">Graduation Day</h1>
      </div>
      <%= image_tag('1.png',  class: "img-responsive", style: " width: 100%") %>
    </div>

    <div class="item">
      <div class="carousel-content">
        <h1 class="carousel">image 2</h1>
      </div>
      <%= image_tag('1.png',  class: "img-responsive", style: "width: 100%") %>
    </div>
  </div>

  <!-- Left and right controls -->

</div>

app/views/home/_index_old.html.erb
<div class="col-sm-12">
  <div class=" col-sm-8" style="padding-right: 0px">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <% if @carousels.count == 0 %>
          <div class="item active">
            <img src="../images/1.jpg">
            <div class="carousel-caption">
              <h1> Default Image </h1>
            </div>
          </div>
        <%else%>
          <% @carousels.each_with_index do |carousel,index| %>
          <!-- Wrapper for slides  -->
            <div class="item  <%=index==0 ? 'active' : "" %>">
              <%= image_tag(carousel.image_url(:img), :class => 'img-responsive img-rounded position') if carousel.image?%>
              <div class="carousel-caption">
                <h1><%= carousel.name %></h1>
              </div>
            </div>
          <%end%>
        <%end%>
      </div>
      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <div class="col-sm-4 carousel-c" >
    <%= link_to 'Claim your Account',  claim_account_claim_index_path, :class => 'btn btn-primary btn-flat' %>
    <div id="info-section">
      <h4>Latest News</h4>
      <% count = 0%>
      <% @announcements.each do |announcement| %>
        <div  id="news">
          <% if count < 4 %>
            <div class="news-li">
               <p><%= link_to  announcement.title.html_safe,   announcement_path(id: announcement.id)%> <br>
                  <%= announcement.created_at.strftime("%B")%> <%=announcement.created_at.strftime("%Y")%></p>
            </div>
            <% count = count + 1%>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="col-sm-12">
  <div class="col-sm-12"> <h4><strong>Events & Reunions</strong></h4></div>
  <% event_count = 0%>
  <% @events.each do |event| %>
      <div class="col-sm-4" id="events">
        <% if event_count < 3 %>
          <h4> <%= link_to  event.title, event_path(id: event.id) %></h4>
          <%= event.date.strftime("%B") %> <%= event.date.strftime("%Y") %><br>
          <%= event.description.truncate(50).html_safe %><br><br>
          <% event_count = event_count + 1%>
        <% end %>
      </div>
  <% end %>
</div>

<style media="screen">
  #events:hover{background-color:  #fff}
  .carousel-c{background: #fff; color: #000}

  #info-section{background-color: #fff;}
  .news-li{height: auto;
    background-color: #fff;
    color: #000;
    border: 1px solid #ccc;
    border-radius: 5px; padding: 5px}
</style>

app/views/home/_slider.html.erb
<!--=== Slider ===-->
<div class="slider-inner">
    <div id="da-slider" class="da-slider">
        <div class="da-slide">
          <h2><span>MULTIMEDIA UNIVERSITY ALUMNI</span> <br /> <i><em>REUNITE & CONNECT </i> <br /> <i>WITH YOUR FRIENDS</i></em></h2>

            <div class="da-img"><%= image_tag('1.jpg',  class: "img-responsive") %></div>
        </div>

        <div class="da-slide">
            <h2><i>GET NOTIFIED</i> <br /> <i>ABOUT UP COMING ALUMNI </i> <br /> <i>EVENTS</i></h2>
            <div class="da-img"><%= image_tag('seminar.jpg',  class: "img-responsive") %></div>
        </div>

        <div class="da-slide">
            <h2><i>HAVE FUN</i> <br /> <i>WITH YOUR BATCH MATES </i> <br /> <i>AND FRIENDS</i></h2>
            <div class="da-img"><%= image_tag('reunite.jpg',  class: "img-responsive") %></div>
        </div>

        <div class="da-arrows">
            <span class="da-arrows-prev"></span>
            <span class="da-arrows-next"></span>
        </div>
    </div>
</div><!--/slider-->
<!--=== End Slider ===-->

app/views/home/index.html.erb
<%#= render partial: 'slider' %>
<%= render partial: 'carousel' %>
<div class="container content">
  <%= render partial: 'announcements' %>
</div>