config/routes.rb
Rails.application.routes.draw do

  resources :messages do
    collection do
      get :sent
    end
  end

  resources :requests
  resources :carousels do
    collection do
      post :publish
      post :unpublish
      delete :destroy
    end
  end
  resources :announcements do
    collection do
      get :carousel
    end
  end
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :events
  resources :jobs
root to: 'home#index'
  get 'home/index'
  resources :home

  resources :graduations
  resources :batches do
    collection do
      post :action_import
    end
  end
  resources :campus
  resources :faculties
  resources :programmes
  devise_for :users
  resources :users

  resources :claim do
    collection do
      get :claim_account
      get :change
    end
  end

  resources :user_profiles do
    get :view_profile
    collection do
      post :upload_profile_picture
      get :privacy
      post :settings
    end
  end

  resources :find_users do
    collection do
      get :map_view
    end
  end

  resources :import do
    collection do
      post :import
      post :importing
    end
  end

  resources :members
  resources :employers do
    collection do
      post :search
      get  :search
    end
  end

end

app/models/_job.rb
class Job < ActiveRecord::Base
  belongs_to :user
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  include Bootsy::Container

  require 'carrierwave/orm/activerecord'
end

app/models/batch.rb
class Batch < ActiveRecord::Base
  has_many :graduations, dependent: :destroy

  RIVACY_OPTIONS = Array["Everyone", "Only Me", "My Batch", "My Programme"]
  MONTHS = Array[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
end

app/models/campu.rb
class Campu < ActiveRecord::Base
  validates :name, presence: true, allow_blank: false
  has_many :faculties,  dependent: :destroy
  has_many :graduations, dependent: :destroy
end

app/models/carousel.rb
class Carousel < ActiveRecord::Base
  mount_uploader :image, CarouselUploader
end

app/models/event.rb
class Event < ActiveRecord::Base
  include Bootsy::Container
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  validates :name, presence: true, allow_blank: false
  has_many :programmes,  dependent: :destroy
  belongs_to :campus
  has_many :graduations, dependent: :destroy

  include ::Importable
   IMPORT_ENABLED = {
     :name => {exact: "name", is_identifier: true}
   }
end

app/models/graduation.rb
class Graduation < ActiveRecord::Base
  belongs_to :user
  belongs_to :batch
  belongs_to :programme
  belongs_to :faculty
  belongs_to :campu

  include ::Importable
   IMPORT_ENABLED = {
     :user_id => {exact: "Student Id", is_identifier: false},
     :name => {exact: "Student Name", is_identifier: false},
     :last_name => {exact: "Last Name", is_identifier: false},
     :email => {exact: "Email", is_identifier: false},
     :alumni_key => {exact: "Alumni Key", is_identifier: false},
     :batch_id => {exact: "Batch", is_identifier: false},
     :programme_id => {exact: "Programme", is_identifier: false},
     :campu_id => {exact: "Campus", is_identifier: false},
     :faculty_id => {exact: "Faculty", is_identifier: false},
   }
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/programme.rb
class Programme < ActiveRecord::Base
  validates :name, presence: true, allow_blank: false

  has_many :graduations, dependent: :destroy
  belongs_to :faculty
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :is_current_city, :faculty, :programme, :batch, :campus
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  geocoded_by :city
  after_validation :geocode

  has_many :graduations, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :messages, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  PRIVACY_OPTIONS = Array["Everyone", "Only Me", "My Batch", "My Programme"]

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy, :upload_profile_picture, :privacy, :settings]
  before_filter :authenticate_user!
  # GET /user_profiles
  # GET /user_profiles.json

  def index
    @user = User.find(current_user.id)
    @jobs = @user.jobs
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
  end

  #find users
  def view_profile
   id = params[:user_profile_id]
   session[:user_id] = id
   @user = User.find_by_id(id)
   @jobs = Job.where(:user_id => id)
  end

  # GET /user_profiles/1/edit
  def edit
    @jobs = Job.all.paginate(:page => 1, :per_page => 30)
  end

  def privacy
    @user = User.new
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user = User.new(user_profile_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Your photo was successfully added.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  #Upload profile picture
  def upload_profile_picture
    @user = User.find(current_user.id)
    @user.avatar = params[:file]
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_profiles_url }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

#profile settings
  def settings
    respond_to do |format|
      if @user.update(user_profile_params)
        format.html { redirect_to user_profiles_url, notice: 'privacy options were successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user.update_attributes(user_profile_params)
        format.html { redirect_to user_profiles_url, notice: 'User profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: 'User profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user).permit(:name, :id_number, :phone, :avatar, :email, :city, :country, :location_privacy_option, :contact_privacy_option, :job_privacy_option, :social_privacy_option,:facebook,:twitter,:linkedin,:instagram, :is_job_seeker)
    end
end

app/helpers/campus_helper.rb
module CampusHelper
end

app/helpers/claim_helper.rb
module ClaimHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_profiles/_bio.html.erb
<div class="panel panel-profile">
  <div class="panel-heading overflow-h">
    <h2 class="panel-title heading-sm pull-left">
      <% if current_user.id == @user.id %>
        <%= link_to   edit_user_profile_path(current_user.id), style: 'color: #205081' do %>
          <span class="glyphicon glyphicon-pencil"> Profile & Settings</span>
        <% end %>
      <% else %>
        My Contact
      <% end %>
    </h2>
  </div>
  <div class="panel-body">
    <ul class="list-unstyled social-contacts-v2">

      <%= render partial: 'contact' %>
      <li>
        <% if @user.graduations.any? %>
          <i class="rounded-x gm fa fa-graduation-cap"></i>
          <% @user.graduations.each do |x|%>
            <%= x.batch.month%> / <%= x.batch.year%>
          <%end%>
          <br>
          <% @user.graduations.each do |x|%>
            <%= x.programme.name%>,
          <%end%>
          <br>
          <% @user.graduations.each do |x|%>
            <% if !x.faculty.nil? %>
              <%= x.faculty.name%>,
            <% end %>
          <%end%>
          <br>
          <% @user.graduations.each do |x|%>
            <% if !x.campu.nil? %>
              <%= x.campu.name%>.
            <% end %>
          <%end%>
        <%end%>
      </li>
    </ul>
  </div>
</div>

app/views/user_profiles/_contact.html.erb
<% if current_user != @user%>
  <% if @user.contact_privacy_option != "Only Me" %>
    <%if @user.contact_privacy_option == "My Batch"%>
      <% if @user.graduations.map { |b| b.batch} & current_user.graduations.map { |s| s.batch }%>
        <li><i class="rounded-x gm fa fa-envelope"></i> <%= @user.email%></li>
        <% if !@user.phone.nil? %>
          <li><i class="rounded-x gm fa fa-phone"></i> <%= @user.phone%></li>
         <%end%>
      <% end %>
    <%elsif @user.contact_privacy_option == "My Programme"%>
      <% if @user.graduations.map { |p| p.programme  }& current_user.graduations.map { |p| p.programme  } %>
        <li><i class="rounded-x gm fa fa-envelope"></i> <%= @user.email%></li>
        <% if !@user.phone.nil? %>
          <li><i class="rounded-x gm fa fa-phone"></i> <%= @user.phone%></li>
        <%end%>
      <%end%>
    <% end %> <!--if contact_privacy_otpion == My Batch -->
  <% end %><!--if social != Only Me -->
<%else%>
<li><i class="rounded-x gm fa fa-envelope"></i> <%= @user.email%></li>
<% if !@user.phone.nil? %>
  <li><i class="rounded-x gm fa fa-phone"></i> <%= @user.phone%></li>
 <%end%>
<%end%>

app/views/user_profiles/_edit_privacy.html.erb
<%= semantic_form_for @user, url: user_profile_path(@user), html: {class: "sky-form", id: "sky-form3"} do |f| %>
  <%= f.input :location_privacy_option, as: :select, collection: User::PRIVACY_OPTIONS.first(User::PRIVACY_OPTIONS.size()) %>
  <hr>
  <%= f.input :social_privacy_option, as: :select, collection: User::PRIVACY_OPTIONS.first(User::PRIVACY_OPTIONS.size()) %>
  <hr>
  <%= f.input :contact_privacy_option, as: :select, collection: User::PRIVACY_OPTIONS.first(User::PRIVACY_OPTIONS.size()) %>
  <hr>
  <%= f.input :job_privacy_option, as: :select, collection: User::PRIVACY_OPTIONS.first(User::PRIVACY_OPTIONS.size()) %>
   <%= f.check_box :is_job_seeker %> <strong>  Let employers find me </strong>
  <hr>
  <%= f.submit "Save Changes", class: 'btn-u' %>
<% end %>

app/views/user_profiles/_edit_socials.html.erb
<%= semantic_form_for @user, url: user_profile_path(@user), html: {class: "sky-form", id: "sky-form3"} do |f| %>
  <div style="padding-bottom: 20px">
    <%= f.text_field :facebook, placeholder: 'Facebook', style: 'width: 100%; height: 34px;' %>
  </div>

  <div style="padding-bottom: 20px">
    <%= f.text_field :twitter,  placeholder: 'Twitter', style: 'width: 100%; height: 34px;' %>
  </div>

  <div style="padding-bottom: 20px">
    <%= f.text_field :instagram,  placeholder: 'Instagram', style: 'width: 100%; height: 34px;' %>
  </div>

  <div style="padding-bottom: 20px">
    <%= f.text_field :linkedin,  placeholder: 'Linkedin', style: 'width: 100%; height: 34px;' %>
  </div>

  <%= f.submit "Save Changes", class: 'btn-u' %>
<% end %>

app/views/user_profiles/_experience.html.erb
<li>
    <time datetime="" class="cbp_tmtime">
      <span><%= job.title %></b>[current]</p></span>
         <span>
            <% if !job.from.nil? && !job.to.nil? %>
              From <%= job.from.strftime("%B %Y") %>
            <% end %>
          </span>
      </time>
    <i class="cbp_tmicon rounded-x hidden-xs"></i>
    <div class="cbp_tmlabel">
      <h2><%= job.company %></h2>
      <h3><%= job.city %> <%= job.country %></h3>
      <p><%= job.description%></p>
    </div>
</li>

app/views/user_profiles/_index.html.erb
<div class=" col-sm-12" style="padding-top :5px">
  <div class="col-sm-2" style="padding-left :0px; padding-right 25px">
    <div id="image_container">
      <%= image_tag(@user.avatar_url(:thumb), :class => 'img-responsive img-rounded position') %>
      <%= render 'profile_photo'%>
    </div>
  </div>
  <div class="col-sm-4">
      <font size="6"> <b><%= @user.name%></b></font>
      <font size="3">
      <p><%= @user.city%>, <%= @user.country%></p>
        <%= render 'profile'%>
        <div class="col-sm-1 pad">
          <i class="fa fa-graduation-cap"></i>
        </div>
        <div class="col-sm-9 pad">
          <font size="2">
          <% @user.graduations.each do |x|%>
           <%= x.batch.month%> / <%= x.batch.year%>
           <%end%>
           <% @user.graduations.each do |x|%>
            <%= x.programme.name%>,
            <%end%>
            <% @user.graduations.each do |x|%>
            <%= x.faculty.name%>,
            <%end%>
            <% @user.graduations.each do |x|%>
            <%= x.campu.name%>.
            <%end%>
          </font>
        </div>
    </div>
    <div class="col-sm-4">
      <%= link_to   edit_user_profile_path(current_user.id), :class => 'btn btn-primary btn-sm pad' do %><span class="glyphicon glyphicon-edit">Edit Profile</span> <% end %>
        <%= image_tag "http://maps.google.com/maps/api/staticmap?size=400x150 &maptype=roadmap&zoom=14&markers=#{@user.city}%2C#{@user.country}" %>
        <%= @user.city %>,  <%= @user.country %>.<br>
    </div>
</div>
<div class="col-sm-12">
  <div class="row pad">
    <br>
    <div class="col-sm-2">
      <% if !@user.facebook.blank?%>
        <a href="<%= @user.facebook %>"> <i class="fa fa-facebook-square"></i></a>
      <% end %>
    </div>
    <div class="col-sm-2">
      <% if !@user.linkedin.blank?%>
        <a href="<%= @user.linkedin %>"><i class="fa fa-linkedin-square"></i></a>
      <% end %>
    </div>
    <div class="col-sm-2">
      <% if !@user.twitter.blank?%>
        <a href="<%= @user.twitter %>"><i class="fa fa-twitter-square"></i></a>
      <% end %>
    </div>
    <div class="col-sm-2">
      <% if !@user.instagram.blank?%>
        <a href="<%= @user.instagram%>"><i class="fa fa-instagram"></i></a>
      <% end %>
    </div>
</div>
<div class="col-sm-12 pad">
  <div class="row">
          <% @jobs.each do |job|%>
            <% if job.user_id == current_user.id %>
              <% if job.current == true%>
              <div class="col-sm-4">
                <p>
                  <b><%= job.title %></b>[current]</p>
                  <p>  <%= job.company %> <%= job.city %>
                    <%= job.country %>
                  <p>
                   <% if !job.from.nil? && !job.to.nil? %>
                       From <%= job.from.strftime("%B %Y") %>
                   <% end %>
                 </p>
              </div>
              <div class="col-sm-1">
                <p>
                  <%= link_to job, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary btn-sm' do %> <span class="glyphicon glyphicon-remove"></span><% end %>
                </p>
              </div>
            <% else %>
            <div class="col-sm-4">
              <p>
                <b><%= job.title %></b></p>
                <p>  <%= job.company %> <%= job.city %>
                <%= job.country %>
                <p>
                 <% if !job.from.nil? && !job.to.nil? %>
                     From <%= job.from.strftime("%B %Y") %> to <%= job.to.strftime("%B %Y")  %>
                 <% end %>
               </p>
            </div>
            <div class="col-sm-1">
              <p>
                <%= link_to job, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary btn-sm' do %> <span class="glyphicon glyphicon-remove"></span><% end %>
              </p>
            </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </font>

      <div class="row">
        <div class="col-sm-2">
          Location privacy:<br>
          <b><%= @user.location_privacy_option %></b>
        </div>
        <div class="col-sm-3">
          Social privacy: <br>
        <b>  <%= @user.social_privacy_option %></b>
        </div>
        <div class="col-sm-3">
          Contact privacy: <br>
          <b><%= @user.contact_privacy_option %></b>
        </div>
        <div class="col-sm-3">
          Job privacy: <br>
          <b><%= @user.job_privacy_option %></b>
        </div>
      </div>
    </div>
</div>

<style>
   span{color:white}
   .position{position:relative;}
   #image_container{width:300px; height:auto }
   .pad{padding: 0px}
   .pad-left{padding-left :15px}
   .pad-bottom{padding-bottom: 0px;}
</style>

<script type="text/javascript">
  $(document).ready(function () {
    $(this).find("#btn").hide();
    $(document).on('mouseenter', '#image_container', function () {
        $(this).find("#btn").show();
    }).on('mouseleave', '#image_container', function () {
        $(this).find("#btn").hide();
    });
  });
</script>

app/views/user_profiles/_profile.html.erb
  <% if !@user.phone.nil? %>
    <div class="col-sm-1">
      <i class="fa fa-phone"></i>
    </div>
    <div class="col-sm-11">
      <%= @user.phone %>
    </div>
    <% else %>

    <% end %>


    <% if !@user.email.nil?%>
      <div class="col-sm-1">
        <i class="fa fa-envelope-o"></i>
      </div>
      <div class="col-sm-11">
        <%= @user.email%>
      </div>
    <% else %>
        N/A
    <% end %>

    <div class="panel panel-profile">
        <div class="panel-heading overflow-h">
            <h2 class="panel-title heading-sm pull-left"><i class="fa fa-pencil"></i> Social Contacts <small>(option 1)</small></h2>
            <a href="#"><i class="fa fa-cog pull-right"></i></a>
        </div>
        <div class="panel-body">
             <ul class="list-unstyled social-contacts-v2">
                <li><i class="rounded-x tw fa fa-twitter"></i> <a href="#">edward.rooster</a></li>
                <li><i class="rounded-x fb fa fa-facebook"></i> <a href="#">Edward Rooster</a></li>
                <li><i class="rounded-x sk fa fa-skype"></i> <a href="#">edwardRooster77</a></li>
                <li><i class="rounded-x gp fa fa-google-plus"></i> <a href="#">rooster77edward</a></li>
                <li><i class="rounded-x gm fa fa-envelope"></i> <a href="#">edward77@gmail.com</a></li>
            </ul>
        </div>
    </div>

app/views/user_profiles/_skills.html.erb
<div class="panel panel-profile">
  <div class="panel-heading overflow-h">
    <h2 class="panel-title heading-sm pull-left">
      <span class="fa fa-lightbulb-o"> Skills</span>
    </h2>
  </div>
  <div class="panel-body">
    <% if @user.jobs.any? %>
      <%= @user.jobs.last.skills %>
    <% else %>
      <strong style="color: lightblue"><em>Not Specified</em></strong>
    <% end %>
  </div>
</div>

app/views/user_profiles/bview_profile.html.erb
<div class=" container content profile">
  <div class="col-sm-3" style="padding-left :0px; padding-right 25px">
    <div id="image_container">
      <% if @user.avatar.blank? %>
      <%= image_tag 'default.jpg', :class => 'img-responsive img-rounded position', :style => "width: 200px"%>
      <%else%>
        <%= image_tag(@user.avatar_url(:thumb), :class => 'img-responsive img-rounded position') if @user.avatar?%>
      <%end%>
    </div>
  </div>
  <div class="col-sm-4">
      <font size="6"> <b><%= @user.name%></b></font>
      <font size="3">
      <p><%= @user.city%> <%= @user.country%></p>
        <%= render 'profile'%>
        <div class="col-sm-1 pad">
          <i class="fa fa-graduation-cap"></i>
        </div>
        <div class="col-sm-9 pad">
          <% @user.graduations.each do |x|%>
           <%= x.batch.month%> / <%= x.batch.year%>,
           <%end%>

           <% @user.graduations.each do |x|%>
            <%= x.programme.name%>,
            <%end%>

            <% @user.graduations.each do |x|%>
            <%= x.faculty.name%>,
            <%end%>

            <% @user.graduations.each do |x|%>
            <%= x.campu.name%>.
            <%end%>
        </div>
    </div>

    <div class="col-sm-4">
      <div class="row pad">
        <%= image_tag "http://maps.google.com/maps/api/staticmap?size=425x200 &maptype=roadmap&zoom=14&markers=#{@user.city}%2C#{@user.country}" %>
      <font size="4">  <%= @user.city %>,  <%= @user.country %>.</font>
      </div>
    </div>
</div>

<div class="col-sm-12">
      <div class="row pad-left">
        <%= render 'socials' %>
      </div>
      <div class="row pad">
        <%= render 'work_history' %>
      </div>
  </font>
</div>
<%if current_user.is_employer %>
  <%= link_to "Back",   search_employers_path, class: 'btn btn-primary btn-md' %>
<%end%>



<style>
   span{color:white}
   .position{position:relative;}
   #image_container{width:300px; height:auto }
   .pad{padding: 0px}
   .pad-left{padding-left :15px}
   .pad-bottom{padding-bottom: 0px;}
</style>

<script type="text/javascript">
  $(document).ready(function () {
    $(this).find("#btn").hide();
    $(document).on('mouseenter', '#image_container', function () {
        $(this).find("#btn").show();
    }).on('mouseleave', '#image_container', function () {
        $(this).find("#btn").hide();
    });
  });
</script>

app/views/user_profiles/edit.html.erb
<div class="container content profile">
  <div class="col-md-12">
    <div class="profile-body margin-bottom-20">
      <div class="tab-v1">
        <ul class="nav nav-justified nav-tabs">
            <li class="active"><a data-toggle="tab" href="#profile">Edit Profile</a></li>
            <li><a data-toggle="tab" href="#passwordTab">Edit Jobs</a></li>
            <li><a data-toggle="tab" href="#socials_privacy">Privacy Settings</a></li>
            <li><a data-toggle="tab" href="#socials">Edit Socials</a></li>
        </ul>
        <div class="tab-content">

          <div id="profile" class="profile-edit tab-pane fade in active">
            <h2>Edit Your Profile Info</h2></dd>
            <%= render partial: 'edit_info' %>
          </div>

          <div id="passwordTab" class="profile-edit tab-pane fade">
            <h2 class="pull-left col-sm-10">Manage your Job History</h2>
            <div class="col-sn-2">
               <%= link_to   new_job_path, :class => 'btn-u' do %>
                <span class="fa fa-plus-square"> New Job</span>
              <% end %>
            </div>
            <br>
              <%= render partial: 'edit_jobs' %>
          </div>

          <div id="socials_privacy" class="profile-edit tab-pane fade">
            <h2 class="heading-md">Social Privacy Settings</h2>
            <p>Below you can select who can see your profile and what they can see.</p>
            <br>
            <%= render partial: 'edit_privacy' %>
          </div>

          <div id="socials" class="profile-edit tab-pane fade">
            <h2 class="heading-md">Update Your Socials</h2>
            <br>
            <%= render partial: 'edit_socials' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user_profiles/find_user.html.erb
<div>
  <%= search_form_for rl: user_profile_path(@user) @q do |f| %>
    <div class="form-control-wrapper">
      <%= f.search_field :user_name_cont, :class => 'form-control empty', :autocomplete => "off" %>
      <div class="floating-label">Name </div>
        <span class="material-input"></span>
    </div>
    <br />

    <div class="dropdown" >
      Class:
      <%= f.select :batch_id_eq, options_for_select([""]+Batch.all.map{|p| [ p.month.strftime("%B") << " " << p.year.strftime("%Y"), p.id ]}, {:include_blank => true}) %>
          Programme: <%= f.select :programme_id_eq, options_for_select([""]+Programme.all.map{|p| [p.name, p.id]}, {:include_blank => true}) %>
    </div>
    <br />
      <%= f.submit "Search", :action => "find_users", :class => 'btn btn-primary btn-flat' %>
    <br />
  <% end %>
</div>

app/views/user_profiles/privacy.html.erb
<%= semantic_form_for @user, url:settings_user_profiles_path(id: current_user.id) do |f|%>
  <div class="container content">
    <div class="col-sm-2 ">
      <%= f.input :location_privacy_option, as: :select, collection: [""]+User::PRIVACY_OPTIONS.first(User::PRIVACY_OPTIONS.size()), :class => 'control'%>
    </div>
    <div class="col-sm-2 ">
      <%= f.input :social_privacy_option,as: :select, collection: [""]+User::PRIVACY_OPTIONS.first(User::PRIVACY_OPTIONS.size()), :class => 'control'%>
    </div>
    <div class="col-sm-2">
      <%= f.input :contact_privacy_option, as: :select, collection: [""]+User::PRIVACY_OPTIONS.first(User::PRIVACY_OPTIONS.size()), :class => 'control'%>
    </div>
    <div class="col-sm-2">
      <%= f.input :job_privacy_option, as: :select,collection: [""]+User::PRIVACY_OPTIONS.first(User::PRIVACY_OPTIONS.size()), :class => 'control'%>
    </div>
    <div class="col-sm-2" style="padding-top: 15px">
      Looking for a job
      <%= f.check_box :is_job_seeker%>
    </div>
    <div class="col-sm-2">
      <%= f.submit "Save", :class => "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', user_profile_path(@user) %> |
<%= link_to 'Back', user_profiles_path %>