config/routes.rb
Rails.application.routes.draw do

  resources :messages do
    collection do
      get :sent
    end
  end

  resources :requests
  resources :carousels do
    collection do
      post :publish
      post :unpublish
      delete :destroy
    end
  end
  resources :announcements do
    collection do
      get :carousel
    end
  end
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :events
  resources :jobs
root to: 'home#index'
  get 'home/index'
  resources :home

  resources :graduations
  resources :batches do
    collection do
      post :action_import
    end
  end
  resources :campus
  resources :faculties
  resources :programmes
  devise_for :users
  resources :users

  resources :claim do
    collection do
      get :claim_account
      get :change
    end
  end

  resources :user_profiles do
    get :view_profile
    collection do
      post :upload_profile_picture
      get :privacy
      post :settings
    end
  end

  resources :find_users do
    collection do
      get :map_view
    end
  end

  resources :import do
    collection do
      post :import
      post :importing
    end
  end

  resources :members
  resources :employers do
    collection do
      post :search
      get  :search
    end
  end

end

app/models/_job.rb
class Job < ActiveRecord::Base
  belongs_to :user
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  include Bootsy::Container

  require 'carrierwave/orm/activerecord'
end

app/models/batch.rb
class Batch < ActiveRecord::Base
  has_many :graduations, dependent: :destroy

  RIVACY_OPTIONS = Array["Everyone", "Only Me", "My Batch", "My Programme"]
  MONTHS = Array[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
end

app/models/campu.rb
class Campu < ActiveRecord::Base
  validates :name, presence: true, allow_blank: false
  has_many :faculties,  dependent: :destroy
  has_many :graduations, dependent: :destroy
end

app/models/carousel.rb
class Carousel < ActiveRecord::Base
  mount_uploader :image, CarouselUploader
end

app/models/event.rb
class Event < ActiveRecord::Base
  include Bootsy::Container
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  validates :name, presence: true, allow_blank: false
  has_many :programmes,  dependent: :destroy
  belongs_to :campus
  has_many :graduations, dependent: :destroy

  include ::Importable
   IMPORT_ENABLED = {
     :name => {exact: "name", is_identifier: true}
   }
end

app/models/graduation.rb
class Graduation < ActiveRecord::Base
  belongs_to :user
  belongs_to :batch
  belongs_to :programme
  belongs_to :faculty
  belongs_to :campu

  include ::Importable
   IMPORT_ENABLED = {
     :user_id => {exact: "Student Id", is_identifier: false},
     :name => {exact: "Student Name", is_identifier: false},
     :last_name => {exact: "Last Name", is_identifier: false},
     :email => {exact: "Email", is_identifier: false},
     :alumni_key => {exact: "Alumni Key", is_identifier: false},
     :batch_id => {exact: "Batch", is_identifier: false},
     :programme_id => {exact: "Programme", is_identifier: false},
     :campu_id => {exact: "Campus", is_identifier: false},
     :faculty_id => {exact: "Faculty", is_identifier: false},
   }
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/programme.rb
class Programme < ActiveRecord::Base
  validates :name, presence: true, allow_blank: false

  has_many :graduations, dependent: :destroy
  belongs_to :faculty
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :is_current_city, :faculty, :programme, :batch, :campus
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  geocoded_by :city
  after_validation :geocode

  has_many :graduations, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :messages, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  PRIVACY_OPTIONS = Array["Everyone", "Only Me", "My Batch", "My Programme"]

end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:show, :edit, :update, :destroy, :search]

  # GET /employers
  # GET /employers.json
  def index
    @user = User.new
  end

  def search
    @search = Graduation.ransack(params[:q])
    @users = @search.result(:distinct => true).includes(:user).where("users.is_job_seeker is  true").references(:users).paginate(:page => params[:page], :per_page => 5)
  end
  # GET /employers/1
  # GET /employers/1.json
  def show
  end

  # GET /employers/new
  def new
    @user = User.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @user = User.new(user_params)
    @user.is_employer = true
    @user.is_graduate = false
    @user.save
    respond_to do |format|
      if @user.save
        format.html { redirect_to  employers_path, notice: 'Your account was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @user.update(employer_params)
        format.html { redirect_to @user, notice: 'Employer was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :student_id, :email, :password, :password_confirmation, :avatar)
    end
end

app/helpers/campus_helper.rb
module CampusHelper
end

app/helpers/claim_helper.rb
module ClaimHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employers/_form.html.erb
<%= form_for(@user, url: employers_path) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-dismissable alert-danger">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="reg-page">
    <div class="input-group margin-bottom-20">
      <span class="input-group-addon"><i class="fa fa-user"></i></span>
      <%= f.text_field :name, autofocus: true, placeholder: 'Name', autocomplete: "off", :class => 'form-control empty' %>
    </div>

    <div class="input-group margin-bottom-20">
      <span class="input-group-addon"><i class="fa fa-user"></i></span>
      <%= f.text_field :student_id, placeholder: 'Username', autocomplete: "off", :class => 'form-control empty' %>
    </div>

    <div class="input-group margin-bottom-20">
      <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
      <%= f.email_field :email, placeholder: 'Email', autocomplete: "off", :class => 'form-control empty' %>
    </div>

    <div class="input-group margin-bottom-20">
      <span class="input-group-addon"><i class="fa fa-lock"></i></span>
      <%= f.password_field :password, autofocus: false, placeholder: 'Password', autocomplete: "off", :class => 'form-control empty' %>
    </div>

    <div class="input-group margin-bottom-20">
      <span class="input-group-addon"><i class="fa fa-lock"></i></span>
      <%= f.password_field :password, autofocus: false, placeholder: 'Confirm Password', autocomplete: "off", :class => 'form-control empty' %>
    </div>

    <div class="row">
      <div class="col-md-6">
        <%= f.submit "Sign Up", :class => 'btn btn-u', style: 'width: 200px;' %>
      </div>
    </div>
  </div>
<% end %>

app/views/employers/_sign_in_modal.html.erb
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div style="padding: 10px">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4>Sign In</h4>
      </div>
      <div class="modal-body">
        <div class="row">
            <%= form_for(:user, as: :user, url: session_path(@user)) do |f| %>
            <div class="reg-page">
              <div class="input-group margin-bottom-20">
                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                <%= f.text_field :student_id, autofocus: true, placeholder: 'username', autocomplete: "off", :class => 'form-control empty' %>
              </div>
              <div class="input-group margin-bottom-20">
                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                <%= f.password_field :password, autofocus: false, placeholder: 'Password', autocomplete: "off", :class => 'form-control empty' %>
              </div>

              <div class="row">
                <div class="col-md-6">
                  <%= f.submit "Login ", :class => 'btn-u pull-right' %>
                </div>
              </div>

              <h4>Forget your Password ?</h4>
              <p>no worries, <a class="color-green" href="#">click here</a> to reset your password.</p>
            </div>
            <br>
            <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employers/_sign_up_modal.html.erb
<div id="sign_up" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div style="padding: 10px">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Employer Sign Up</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <%= render partial: 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employers/edit.html.erb
<h1>Editing Employer</h1>

<%= render 'form' %>

<%= link_to 'Show', @employer %> |
<%= link_to 'Back', employers_path %>

app/views/employers/index.html.erb
<%= render partial: 'sign_in_modal' %>
<%= render partial: 'sign_up_modal' %>
<%#= render partial: 'home/slider' %>
<div class="image-block">
    <div class="container">
        <div class="company-description">
            <h2>Sign Up and discover the best talent of MMU alumni</h2>
            <p>Here you can find our alumni seeking for a job. </p>
            <p>At MMU, we provide the best talent.</p>
            <div class="margin-bottom-20"></div>
        </div>
        <br>
        <br>
        <br>
        <br>
    </div>
</div>

app/views/employers/new.html.erb
<%= render partial: 'form' %>

app/views/employers/search.html.erb
<div class="breadcrumbs">
  <div class="container">
    <h4>Search Job Seekers By Programme And Graduation Year.</h4>
  </div>
</div>
<div class="container content">
  <div class="col-md-9 radius row-margin-bottom-20">
    <%= semantic_form_for @search, url:  search_employers_path do |f| %>
      <div class="col-sm-5  ">
        <strong class="search-label">Programme:</strong>
        <%= f.input :programme_id_eq, as: :select, collection: Programme.select("distinct name, id").map{|p| [p.name, p.id]}, :include_blank => true %>
      </div>

      <div class="col-sm-5">
        <strong class="search-label">Class:</strong>
        <%= f.input :batch_id_eq, as: :select, collection: Batch.all.map{|p| ["#{p.month} / #{p.year}", p.id] }, :include_blank => true%>
      </div>

      <div class="col-sm-2">
        <br>
        <%= f.submit "Search", :class => 'btn-u'%>
      </div>
    <% end %>
  </div>
</div>

<div class="container content profile">
  <div class="col-md-9">
    <div class="profile-body margin-bottom-20">
      <div class="row margin-bottom-20">
        <% if @users.any? %>
          <% @users.each do |user| %>
              <div class="col-sm-6 sm-margin-bottom-20">
                  <div class="profile-blog">
                    <% if user.user.avatar.blank? %>
                      <%= link_to image_tag("user.jpg", class: 'rounded-x'), user_profile_view_profile_path(user.user.id) %>
                    <%else%>
                      <%=link_to  image_tag(user.user.avatar, :class => 'rounded-x'), user_profile_view_profile_path(user.user.id)%>
                    <%end%>
                      <div class="name-location">
                          <strong><%= user.user.name%></strong>
                          <span><%= user.programme.name %></span> <br>
                          <span>
                            <% if user.user.jobs.includes(:jobs).any?%>
                              <%= user.user.jobs.last.title%>,
                            <%= user.user.jobs.last.company%>
                            <% end %>
                          </span>
                      </div>
                      <div class="clearfix margin-bottom-20"></div>
                      <p></p>
                      <hr>
                      <ul class="list-inline share-list">
                          <li><i class="fa fa-phone"></i><%= user.user.phone %></li>
                          <li><i class="fa fa-envelope"></i><%= user.user.email %></li>
                      </ul>
                  </div>
                  <br>
              </div>
          <% end %>
        <% else %>
          <div class="profile-blog">
            <strong>No Record found!  </strong>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  $('label').hide();
</script>

app/views/employers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_employer_path(@employer) %> |
<%= link_to 'Back', employers_path %>